// Server-side loaders for the generated reference JSON under content/reference/.
// The files are committed build inputs (generated by `pnpm run generate:reference`), so a
// missing directory means the pipeline has not run — pages render empty and we warn instead
// of crashing unrelated builds and tests.

import path from "node:path";
import { readJsonIfExists, readTextIfExists } from "../content/fs";
import type { PackageDocs, ReferenceIndex, ReferenceIndexEntry } from "./types";

const REFERENCE_ROOT =
  process.env.KATARI_REFERENCE_ROOT ??
  path.join(/*turbopackIgnore: true*/ process.cwd(), "content", "reference");

export function listReferencePackages(): ReferenceIndexEntry[] {
  const raw = readJsonIfExists(path.join(REFERENCE_ROOT, "index.json"));
  if (raw === undefined) {
    console.warn(
      "[reference] content/reference/index.json not found — run `pnpm run generate:reference`",
    );
    return [];
  }
  // The index is produced by our own generator; a version-checked cast keeps the hot path
  // free of a full structural validation over megabytes of JSON.
  return (raw as ReferenceIndex).packages;
}

/** The package's README.md as mirrored from its pinned tarball by the generator; undefined
 *  when the package ships none (`hasReadme` on the index entry says the same thing). */
export function getPackageReadme(name: string): string | undefined {
  if (!/^[a-z0-9_-]+$/i.test(name)) return undefined;
  return readTextIfExists(path.join(REFERENCE_ROOT, "readme", `${name}.md`));
}

export function getPackageDocs(name: string): PackageDocs | undefined {
  // Package names come from the generated index, but guard traversal anyway.
  if (!/^[a-z0-9_-]+$/i.test(name)) return undefined;
  const raw = readJsonIfExists(path.join(REFERENCE_ROOT, `${name}.json`));
  if (raw === undefined) return undefined;
  const docs = raw as PackageDocs;
  if (docs.katariDocsVersion !== 1) {
    throw new Error(
      `content/reference/${name}.json has katariDocsVersion ${docs.katariDocsVersion}; this site understands version 1`,
    );
  }
  return docs;
}
